export const properties = [
    {
        id: 1,
        title: "Luxury Apartment SCBD",
        price: "Rp 8,5 Miliar",
        type: "Apartemen",
        location: "Jakarta Selatan",
        bedrooms: 3,
        bathrooms: 2,
        area: 250,
        image: "/1.jpg",
        facilities: ['Kolam Renang', 'Gym', 'Security 24/7'],
        date: "2024-05-01"
    },
    {
        id: 2,
        title: "Modern House Pondok Indah",
        price: "Rp 12 Miliar",
        type: "Rumah",
        location: "Jakarta Selatan",
        bedrooms: 4,
        bathrooms: 3,
        area: 400,
        image: "/2.jpg",
        facilities: ['Parkir', 'Taman'],
        date: "2024-05-02"
    },
    {
        id: 3,
        title: "Penthouse Kuningan City",
        price: "Rp 25 Miliar",
        type: "Apartemen",
        location: "Jakarta Selatan",
        bedrooms: 5,
        bathrooms: 4,
        area: 500,
        image: "/3.jpg",
        facilities: ['Kolam Renang', 'Rooftop Garden', 'Smart Home'],
        date: "2024-05-03"
    },
    {
        id: 4,
        title: "Townhouse BSD City",
        price: "Rp 6,8 Miliar",
        type: "Rumah",
        location: "Tangerang",
        bedrooms: 3,
        bathrooms: 2,
        area: 280,
        image: "/4.jpg",
        facilities: ['Carport', 'Taman'],
        date: "2024-05-04"
    },
    {
        id: 5,
        title: "Office Space Sudirman",
        price: "Rp 35 Miliar",
        type: "Komersial",
        location: "Jakarta Pusat",
        bedrooms: 0,
        bathrooms: 2,
        area: 300,
        image: "/5.jpg",
        facilities: ['Parkir Basement', 'Lift Barang'],
        date: "2024-05-05"
    },
    {
        id: 6,
        title: "Villa Seminyak",
        price: "Rp 45 Miliar",
        type: "Rumah",
        location: "Bali",
        bedrooms: 6,
        bathrooms: 5,
        area: 1200,
        image: "/6.jpg",
        facilities: ['Private Pool', 'Ocean View'],
        date: "2024-05-06"
    },
    {
        id: 7,
        title: "Studio Apartment Menteng",
        price: "Rp 5,2 Miliar",
        type: "Apartemen",
        location: "Jakarta Pusat",
        bedrooms: 1,
        bathrooms: 1,
        area: 150,
        image: "/7.jpg",
        facilities: ['Fully Furnished', 'CCTV'],
        date: "2024-05-07"
    },
    {
        id: 8,
        title: "Retail Space PIK",
        price: "Rp 28 Miliar",
        type: "Komersial",
        location: "Jakarta Utara",
        bedrooms: 0,
        bathrooms: 2,
        area: 450,
        image: "/8.jpg",
        facilities: ['Frontage Road', 'Parkir Luas'],
        date: "2024-05-08"
    },
    {
        id: 9,
        title: "Bungalow Lembang",
        price: "Rp 9,8 Miliar",
        type: "Rumah",
        location: "Bandung",
        bedrooms: 3,
        bathrooms: 2,
        area: 350,
        image: "/9.jpg",
        facilities: ['Taman', 'Green House'],
        date: "2024-05-09"
    },
    {
        id: 10,
        title: "Luxury Suite Kemang",
        price: "Rp 18 Miliar",
        type: "Apartemen",
        location: "Jakarta Selatan",
        bedrooms: 4,
        bathrooms: 3,
        area: 320,
        image: "/10.jpg",
        facilities: ['Private Lift', 'Jacuzzi'],
        date: "2024-05-10"
    },
    {
        id: 11,
        title: "Beachfront Villa Canggu",
        price: "Rp 65 Miliar",
        type: "Rumah",
        location: "Bali",
        bedrooms: 8,
        bathrooms: 6,
        area: 2000,
        image: "/11.jpg",
        facilities: ['Infinity Pool', 'Direct Beach Access'],
        date: "2024-05-11"
    },
    {
        id: 12,
        title: "Kost Eksklusif Tebet",
        price: "Rp 22 Miliar",
        type: "Komersial",
        location: "Jakarta Selatan",
        bedrooms: 12,
        bathrooms: 8,
        area: 800,
        image: "/12.jpg",
        facilities: ['Dapur Bersama', 'Laundry'],
        date: "2024-05-12"
    },
    {
        id: 13,
        title: "Cluster House Bintaro",
        price: "Rp 7,5 Miliar",
        type: "Rumah",
        location: "Tangerang Selatan",
        bedrooms: 3,
        bathrooms: 2,
        area: 300,
        image: "/13.jpg",
        facilities: ['Club House', 'Playground'],
        date: "2024-05-13"
    },
    {
        id: 14,
        title: "Apartment Green Lake City",
        price: "Rp 6,3 Miliar",
        type: "Apartemen",
        location: "Jakarta Barat",
        bedrooms: 2,
        bathrooms: 1,
        area: 180,
        image: "/14.jpg",
        facilities: ['Jogging Track', 'Kids Pool'],
        date: "2024-05-14"
    },
    {
        id: 15,
        title: "Gudang Industri Cikarang",
        price: "Rp 42 Miliar",
        type: "Komersial",
        location: "Bekasi",
        bedrooms: 0,
        bathrooms: 1,
        area: 1500,
        image: "/15.jpg",
        facilities: ['Dock Leveler', 'Parkir Truk'],
        date: "2024-05-15"
    },
    {
        id: 16,
        title: "Resort Villa Ubud",
        price: "Rp 95 Miliar",
        type: "Rumah",
        location: "Bali",
        bedrooms: 10,
        bathrooms: 8,
        area: 3500,
        image: "/16.jpg",
        facilities: ['Spa', 'Restaurant'],
        date: "2024-05-16"
    },
    {
        id: 17,
        title: "Apartment Thamrin City",
        price: "Rp 15 Miliar",
        type: "Apartemen",
        location: "Jakarta Pusat",
        bedrooms: 3,
        bathrooms: 2,
        area: 220,
        image: "/17.jpg",
        facilities: ['Sky Lounge', 'Concierge'],
        date: "2024-05-17"
    },
    {
        id: 18,
        title: "Ruko CBD Karawaci",
        price: "Rp 18 Miliar",
        type: "Komersial",
        location: "Tangerang",
        bedrooms: 0,
        bathrooms: 2,
        area: 350,
        image: "/18.jpg",
        facilities: ['Listrik Industri', 'Akses Tol'],
        date: "2024-05-18"
    },
    {
        id: 19,
        title: "Mansion Ciputat",
        price: "Rp 32 Miliar",
        type: "Rumah",
        location: "Jakarta Selatan",
        bedrooms: 6,
        bathrooms: 5,
        area: 850,
        image: "/19.jpg",
        facilities: ['Home Theater', 'Wine Cellar'],
        date: "2024-05-19"
    },
    {
        id: 20,
        title: "Studio Apartment Bandung",
        price: "Rp 4,5 Miliar",
        type: "Apartemen",
        location: "Bandung",
        bedrooms: 1,
        bathrooms: 1,
        area: 120,
        image: "/20.jpg",
        facilities: ['Co-working Space', 'Cafe'],
        date: "2024-05-20"
    },
    {
        id: 21,
        title: "Villa Puncak",
        price: "Rp 28 Miliar",
        type: "Rumah",
        location: "Bogor",
        bedrooms: 5,
        bathrooms: 4,
        area: 600,
        image: "/21.jpg",
        facilities: ['Fireplace', 'Mountain View'],
        date: "2024-05-21"
    },
    {
        id: 22,
        title: "Kantor Plaza Senayan",
        price: "Rp 120 Miliar",
        type: "Komersial",
        location: "Jakarta Pusat",
        bedrooms: 0,
        bathrooms: 4,
        area: 2000,
        image: "/22.jpg",
        facilities: ['Fiber Optic', 'Parkir Valet'],
        date: "2024-05-22"
    },
    {
        id: 23,
        title: "Cluster BSD Green Office",
        price: "Rp 55 Miliar",
        type: "Komersial",
        location: "Tangerang",
        bedrooms: 0,
        bathrooms: 3,
        area: 900,
        image: "/23.jpg",
        facilities: ['Solar Panel', 'Rainwater Harvesting'],
        date: "2024-05-23"
    },
    {
        id: 24,
        title: "Apartment Pantai Indah Kapuk",
        price: "Rp 9,8 Miliar",
        type: "Apartemen",
        location: "Jakarta Utara",
        bedrooms: 2,
        bathrooms: 2,
        area: 190,
        image: "/24.jpg",
        facilities: ['Marina View', 'Fishing Deck'],
        date: "2024-05-24"
    },
    {
        id: 25,
        title: "Townhouse Surabaya Barat",
        price: "Rp 14 Miliar",
        type: "Rumah",
        location: "Surabaya",
        bedrooms: 4,
        bathrooms: 3,
        area: 380,
        image: "/25.jpg",
        facilities: ['Private Garage', 'Maid Room'],
        date: "2024-05-25"
    },
    {
        id: 26,
        title: "Apartment Superblok MM2100",
        price: "Rp 3,8 Miliar",
        type: "Apartemen",
        location: "Bekasi",
        bedrooms: 1,
        bathrooms: 1,
        area: 140,
        image: "/26.jpg",
        facilities: ['Shuttle Service', 'Mini Market'],
        date: "2024-05-26"
    },
    {
        id: 27,
        title: "Villa Bukit Jimbaran",
        price: "Rp 75 Miliar",
        type: "Rumah",
        location: "Bali",
        bedrooms: 7,
        bathrooms: 6,
        area: 1800,
        image: "/27.jpg",
        facilities: ['Private Beach', 'Helipad'],
        date: "2024-05-27"
    },
    {
        id: 28,
        title: "Rukan CBD Pluit",
        price: "Rp 24 Miliar",
        type: "Komersial",
        location: "Jakarta Utara",
        bedrooms: 0,
        bathrooms: 2,
        area: 400,
        image: "/28.jpg",
        facilities: ['Dock Door', 'Cargo Lift'],
        date: "2024-05-28"
    },
    {
        id: 29,
        title: "Luxury Penthouse Senopati",
        price: "Rp 68 Miliar",
        type: "Apartemen",
        location: "Jakarta Selatan",
        bedrooms: 4,
        bathrooms: 4,
        area: 480,
        image: "/29.jpg",
        facilities: ['Private Spa', 'Wine Storage'],
        date: "2024-05-29"
    },
    {
        id: 30,
        title: "Resort Land Lombok",
        price: "Rp 150 Miliar",
        type: "Komersial",
        location: "Lombok",
        bedrooms: 0,
        bathrooms: 0,
        area: 5000,
        image: "/30.jpg",
        facilities: ['Beach Club', 'Golf Course'],
        date: "2024-05-30"
    }
];